import Head from 'next/head'

import Header from '../components/Header'
import Footer from '../components/Footer'

import { Jumbo } from '../components/blocks'

// TODO: add robots.txt
// TODO: metadata (+ favicon)

export default function Home() {
	return (
		<>
			<Head>
				<title>Rent my Kangoo!</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<main>
				<Header />
				<Jumbo />
				<Footer />
			</main>
		</>
	)
}
